modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="http://www.github.com/Trikzon/Flora-Doubling/issues"

[[mods]]
modId="floradoubling"
version="${file.jarVersion}"
displayName="Flora Doubling"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/flora-doubling"
#logoFile=""
#credits=""
authors="Trikzon"
description='''
Allows doubling a flower by using bone meal on it
'''

[[dependencies.floradoubling]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.floradoubling]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"
