modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="http://www.github.com/Trikzon/Flora-Doubling/issues"

[[mods]]
modId="flora-doubling"
version="${file.jarVersion}"
displayName="Flora Doubling"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/flora-doubling"
#logoFile=""
#credits=""
authors="Trikzon"
description='''
Allows doubling a flower by using bone meal on it
'''